# Generated by Django 5.0 on 2023-12-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_alter_movie_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dec', models.TextField()),
                ('year', models.IntegerField()),
                ('imp', models.ImageField(upload_to='gellery')),
            ],
        ),
        migrations.DeleteModel(
            name='movie',
        ),
    ]
