# Generated by Django 5.0 on 2023-12-13 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_movies_delete_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='imp',
            new_name='img',
        ),
    ]
